### ISSUE TITLE
Typo in ATE Plot

### ISSUE THREAD

**Issue by pauschae** [xuyiqing/gsynth#1]
In the plot from the users guide:
plot(out, type = "counterfactual", raw = "all")
![grafik](https://user-images.githubusercontent.com/11628946/28012487-3cbd045c-6566-11e7-931d-98d41449cf07.png)
it says treated Avearge instead of treated Average. I noticed this also in my own plots. Therefore its propably a typo in the plot method.

Is there a way to obtain the ggplot object used for the plot directly?

**Comment by xuyiqing** [comment]
Thank you for letting me know. I'll fix this in the next round. Unfortunately, the ggplot object is not stored. But you can check "gsynth.R" file and search for "plot.gsynth" to locate the chunk of code that produces the figure. If you have any trouble, let me know <yiqingxu@ucsd.edu>. Thanks!
