### ISSUE TITLE
安装的时候报错：不存在叫“rlang”这个名字的包，请问应该怎么办？

### ISSUE THREAD

**Issue by shiluoyiqin** [xuyiqing/gsynth#25]
![image](https://user-images.githubusercontent.com/52820583/61122626-dd0ab800-a4d4-11e9-8891-28c6d4a99600.png)

**Comment by GrimTrigger88** [comment]
It looks like DEPENDENCIES needs to be updated:

Imports: Rcpp (>= 0.12.3), ggplot2 (>= 2.1.0), GGally (>= 1.0.1),
        doParallel (>= 1.0.10), foreach (>= 1.4.3), abind (>= 1.4-0), mvtnorm (>= 1.0-6), MASS (>= 7.3.47)
